# Generated by Django 5.2.7 on 2025-10-17 18:39

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Flashcard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('palabra', models.CharField(max_length=100, unique=True)),
                ('traduccion', models.CharField(max_length=100)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='flashcards/')),
                ('next_review', models.DateField(default=django.utils.timezone.now)),
                ('interval', models.IntegerField(default=1)),
            ],
        ),
    ]
